const store={
 clients: JSON.parse(localStorage.getItem("cm_clients")||"null") || [
  {id:"CL-0001",name:"Apex Global Logistics LLP",type:"LLP",pan:"AABCA8891K",gstin:"32AABCA8891K1ZS",mobile:"9876543210",email:"accounts@apex.example",city:"Kannur",assignee:"Admin Principal",status:"Active"},
  {id:"CL-0002",name:"Zenith Software Solutions",type:"Company",pan:"BBVCS9921L",gstin:"29BBVCS9921L1ZO",mobile:"9876501234",email:"finance@zenith.example",city:"Kozhikode",assignee:"Priya S.",status:"Active"}
 ],
 compliances: JSON.parse(localStorage.getItem("cm_compliances")||"null") || [
  {id:"CMP-0001",clientId:"CL-0001",type:"GSTR-3B",period:"Sep 2026",due:"2026-10-20",fee:2500,status:"In Progress",assignee:"Admin Principal",payment:"Pending",docs:"Pending"},
  {id:"CMP-0002",clientId:"CL-0002",type:"TDS 24Q",period:"Q2 FY 2026-27",due:"2026-10-31",fee:1800,status:"Documents Pending",assignee:"Priya S.",payment:"Requested",docs:"Pending"}
 ],
 invoices: JSON.parse(localStorage.getItem("cm_invoices")||"null") || [],
 payments: JSON.parse(localStorage.getItem("cm_payments")||"null") || [],
 credentials: JSON.parse(localStorage.getItem("cm_credentials")||"null") || [],
 documents: JSON.parse(localStorage.getItem("cm_documents")||"null") || [],
 reminders: JSON.parse(localStorage.getItem("cm_reminders")||"null") || [],
 deadlines: JSON.parse(localStorage.getItem("cm_deadlines")||"null") || []
};
const save=()=>Object.keys(store).forEach(k=>localStorage.setItem("cm_"+k,JSON.stringify(store[k])));
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const money=n=>"₹"+Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:2});
const clientName=id=>store.clients.find(c=>c.id===id)?.name||"Unknown Client";
const badge=s=>{let c=["Completed","Paid","Active","Filed"].includes(s)?"success":["Pending","Requested","Documents Pending"].includes(s)?"warning":["Overdue","Rejected","Failed"].includes(s)?"danger":["In Progress","Review"].includes(s)?"info":"primary";return `<span class="badge ${c}">${esc(s)}</span>`};
let currentView="dashboard";

const views={
 dashboard(){return `
  <div class="grid stats">
   ${stat("Active Clients",store.clients.filter(c=>c.status==="Active").length,"fa-users","red","+ Active")}
   ${stat("Open Compliance",store.compliances.filter(c=>!["Completed","Filed"].includes(c.status)).length,"fa-list-check","amber","Needs attention")}
   ${stat("Payment Pending",money(store.compliances.filter(c=>c.payment!=="Paid").reduce((a,c)=>a+Number(c.fee||0),0)),"fa-indian-rupee-sign","green","Outstanding")}
   ${stat("Documents",store.documents.length,"fa-folder-open","blue","Vault files")}
  </div>
  <div class="grid two-col" style="margin-top:16px">
   <div class="card chart-box"><div class="section-head"><div><h2>Compliance Overview</h2><p>Current workload by status</p></div><button class="small-btn" data-view="compliance">View all</button></div><canvas id="statusChart" class="chart"></canvas></div>
   <div class="card"><div class="section-head"><div><h2>Upcoming Due Dates</h2><p>Next compliance deadlines</p></div><button class="small-btn" data-view="calendar">Calendar</button></div><div class="deadline-list">${upcoming().map(c=>`<div class="deadline"><div style="display:flex;justify-content:space-between;gap:8px"><b>${esc(c.type)}</b>${badge(c.status)}</div><small>${esc(clientName(c.clientId))} • ${esc(c.due)}</small></div>`).join("")||empty("No upcoming deadlines")}</div></div>
  </div>
  <div class="card table-card" style="margin-top:16px"><div class="table-toolbar"><div><div class="toolbar-title">Recent Compliance Work</div><div class="kpi-note">Invoices, payment and filing status linked to each record</div></div><button class="primary" data-action="new-compliance"><i class="fa-solid fa-plus"></i> New Compliance</button></div>${complianceTable(store.compliances.slice(0,8))}</div>
 `},
 clients(){return `<div class="card table-card"><div class="table-toolbar"><div class="toolbar-left"><input class="input" id="clientFilter" placeholder="Search client, PAN, GSTIN..."></div><div class="toolbar-right"><button class="primary" data-action="new-client"><i class="fa-solid fa-plus"></i> Add Client</button></div></div><div id="clientTable">${clientTable(store.clients)}</div></div>`},
 compliance(){return `<div class="card table-card"><div class="table-toolbar"><div class="toolbar-left"><input class="input" id="complianceFilter" placeholder="Search compliance or client..."><select class="select" id="statusFilter"><option value="">All Status</option><option>Documents Pending</option><option>In Progress</option><option>Review</option><option>Filed</option><option>Completed</option><option>Overdue</option></select></div><div class="toolbar-right"><button class="primary" data-action="new-compliance"><i class="fa-solid fa-plus"></i> Add Compliance</button></div></div><div id="complianceTable">${complianceTable(store.compliances)}</div></div>`},
 invoices(){return `<div class="card table-card"><div class="table-toolbar"><div><div class="toolbar-title">Compliance Invoices</div><div class="kpi-note">Every compliance can have its own invoice</div></div><button class="primary" data-action="new-invoice"><i class="fa-solid fa-plus"></i> New Invoice</button></div>${invoiceTable()}</div>`},
 payments(){return `<div class="grid stats">${stat("Requested",money(store.payments.filter(p=>p.status==="Requested").reduce((a,p)=>a+p.amount,0)),"fa-paper-plane","amber","Payment requests")}${stat("Paid",money(store.payments.filter(p=>p.status==="Paid").reduce((a,p)=>a+p.amount,0)),"fa-circle-check","green","Collected")}${stat("Pending",store.payments.filter(p=>p.status!=="Paid").length,"fa-clock","red","Transactions")}${stat("Requests",store.payments.length,"fa-receipt","blue","Total requests")}</div><div class="card table-card" style="margin-top:16px"><div class="table-toolbar"><div class="toolbar-title">Payment Requests</div><button class="primary" data-action="new-payment"><i class="fa-solid fa-plus"></i> Request Payment</button></div>${paymentTable()}</div>`},
 calendar(){return `<div class="card"><div class="section-head"><div><h2>Compliance Calendar</h2><p>Due dates across all clients</p></div><button class="primary" data-action="new-compliance"><i class="fa-solid fa-calendar-plus"></i> Add Due Date</button></div><div class="grid three-col">${calendarCards()}</div></div>`},
 documents(){return `<div class="card table-card"><div class="table-toolbar"><div><div class="toolbar-title">Client Document Vault</div><div class="kpi-note">Upload, preview and download client documents</div></div><button class="primary" data-action="upload-doc"><i class="fa-solid fa-cloud-arrow-up"></i> Upload Document</button></div>${documentTable()}</div>`},
 credentials(){return `<div class="card table-card"><div class="table-toolbar"><div><div class="toolbar-title">Credentials Vault</div><div class="kpi-note">Sensitive access records; passwords are masked</div></div><button class="primary" data-action="new-credential"><i class="fa-solid fa-plus"></i> Add Credential</button></div>${credentialTable()}</div>`},
 reminders(){return `<div class="card table-card"><div class="table-toolbar"><div><div class="toolbar-title">Reminders & Payment Requests</div><div class="kpi-note">Track every client communication</div></div><button class="primary" data-action="new-reminder"><i class="fa-solid fa-bell"></i> New Reminder</button></div>${reminderTable()}</div>`},
 settings(){return `<div class="grid two-col"><div class="card"><div class="section-head"><div><h2>Application Settings</h2><p>Local development configuration</p></div></div><div class="notice info">This build uses browser local storage by default so you can test every module immediately. Firebase can be connected later through the data layer without redesigning the UI.</div><div style="margin-top:14px"><button class="small-btn red" data-action="reset-data">Reset demo data</button></div></div><div class="card"><h2 style="font-size:14px">Production checklist</h2><div class="deadline-list" style="margin-top:12px">${["Firebase Authentication","Firestore security rules","Firebase Storage for documents","Payment gateway / UPI integration","WhatsApp / email provider","Server-side audit logging"].map(x=>`<div class="deadline"><b>${x}</b><small>Connect before production deployment</small></div>`).join("")}</div></div></div>`}
};

function stat(title,value,icon,color,note){return `<div class="card stat"><div class="stat-top"><span>${title}</span><span class="stat-icon ${color}"><i class="fa-solid ${icon}"></i></span></div><div class="stat-value">${value}</div><div class="trend ${color==="green"?"positive":color==="amber"?"warning":"info"}">${note}</div></div>`}
function empty(t){return `<div class="empty"><i class="fa-regular fa-folder-open"></i><div>${t}</div></div>`}
function upcoming(){return [...store.compliances].sort((a,b)=>a.due.localeCompare(b.due)).slice(0,5)}
function complianceTable(rows){return `<div class="table-wrap"><table><thead><tr><th>Compliance</th><th>Client</th><th>Period</th><th>Due</th><th>Fee</th><th>Status</th><th>Payment</th><th></th></tr></thead><tbody>${rows.map(c=>`<tr><td><b>${esc(c.type)}</b><small style="display:block;color:#98a2b3;font-size:9px">${esc(c.id)}</small></td><td>${esc(clientName(c.clientId))}</td><td>${esc(c.period)}</td><td>${esc(c.due)}</td><td class="amount">${money(c.fee)}</td><td>${badge(c.status)}</td><td>${badge(c.payment||"Pending")}</td><td><div class="actions"><button class="small-btn" data-edit-compliance="${c.id}"><i class="fa-solid fa-pen"></i></button><button class="small-btn red" data-payment="${c.id}">Pay</button></div></td></tr>`).join("")}</tbody></table></div>`}
function clientTable(rows){return `<div class="table-wrap"><table><thead><tr><th>Client</th><th>PAN / GSTIN</th><th>Type</th><th>Contact</th><th>Assignee</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(c=>`<tr><td class="client-cell"><strong>${esc(c.name)}</strong><small>${esc(c.id)} • ${esc(c.city)}</small></td><td><b>${esc(c.pan)}</b><small style="display:block;color:#98a2b3">${esc(c.gstin||"—")}</small></td><td>${esc(c.type)}</td><td>${esc(c.mobile)}<small style="display:block;color:#98a2b3">${esc(c.email)}</small></td><td>${esc(c.assignee)}</td><td>${badge(c.status)}</td><td><div class="actions"><button class="small-btn" data-edit-client="${c.id}">Edit</button><button class="small-btn red" data-delete-client="${c.id}"><i class="fa-solid fa-trash"></i></button></div></td></tr>`).join("")}</tbody></table></div>`}
function invoiceTable(){return `<div class="table-wrap"><table><thead><tr><th>Invoice</th><th>Client</th><th>Compliance</th><th>Date</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>${store.invoices.map(i=>`<tr><td><b>${esc(i.id)}</b></td><td>${esc(clientName(i.clientId))}</td><td>${esc(i.compliance)}</td><td>${esc(i.date)}</td><td class="amount">${money(i.total)}</td><td>${badge(i.status)}</td><td><button class="small-btn" data-print-invoice="${i.id}"><i class="fa-solid fa-print"></i> Print</button></td></tr>`).join("")||`<tr><td colspan="7">${empty("No invoices yet. Create one from a compliance record.")}</td></tr>`}</tbody></table></div>`}
function paymentTable(){return `<div class="table-wrap"><table><thead><tr><th>Request</th><th>Client</th><th>Purpose</th><th>Amount</th><th>Requested</th><th>Status</th><th></th></tr></thead><tbody>${store.payments.map(p=>`<tr><td><b>${esc(p.id)}</b></td><td>${esc(clientName(p.clientId))}</td><td>${esc(p.purpose)}</td><td class="amount">${money(p.amount)}</td><td>${esc(p.date)}</td><td>${badge(p.status)}</td><td><button class="small-btn green" data-mark-paid="${p.id}">Mark Paid</button></td></tr>`).join("")||`<tr><td colspan="7">${empty("No payment requests yet.")}</td></tr>`}</tbody></table></div>`}
function calendarCards(){return upcoming().map(c=>`<div class="mini-card"><div style="display:flex;justify-content:space-between;gap:5px">${badge(c.status)}<small>${esc(c.due)}</small></div><b style="font-size:13px">${esc(c.type)}</b><small>${esc(clientName(c.clientId))}</small><div class="progress" style="margin-top:12px"><span style="width:${c.status==="Completed"?100:c.status==="In Progress"?55:25}%"></span></div></div>`).join("")||empty("No deadlines")}
function documentTable(){return `<div class="table-wrap"><table><thead><tr><th>Document</th><th>Client</th><th>Category</th><th>Uploaded</th><th>Size</th><th></th></tr></thead><tbody>${store.documents.map(d=>`<tr><td><i class="fa-solid fa-file" style="color:var(--primary);margin-right:7px"></i><b>${esc(d.name)}</b></td><td>${esc(clientName(d.clientId))}</td><td>${badge(d.category)}</td><td>${esc(d.date)}</td><td>${esc(d.size)}</td><td><button class="small-btn" data-download-doc="${d.id}"><i class="fa-solid fa-download"></i> Download</button></td></tr>`).join("")||`<tr><td colspan="6">${empty("No documents uploaded.")}</td></tr>`}</tbody></table></div>`}
function credentialTable(){return `<div class="table-wrap"><table><thead><tr><th>Client</th><th>Portal</th><th>Username</th><th>Password</th><th>Updated</th><th></th></tr></thead><tbody>${store.credentials.map(c=>`<tr><td>${esc(clientName(c.clientId))}</td><td><b>${esc(c.portal)}</b></td><td>${esc(c.username)}</td><td>•••••••• <button class="link" data-show-pass="${c.id}">show</button></td><td>${esc(c.date)}</td><td><button class="small-btn" data-delete-cred="${c.id}">Delete</button></td></tr>`).join("")||`<tr><td colspan="6">${empty("No credentials recorded.")}</td></tr>`}</tbody></table></div>`}
function reminderTable(){return `<div class="table-wrap"><table><thead><tr><th>Reminder</th><th>Client</th><th>Channel</th><th>Purpose</th><th>Date</th><th>Status</th></tr></thead><tbody>${store.reminders.map(r=>`<tr><td><b>${esc(r.id)}</b></td><td>${esc(clientName(r.clientId))}</td><td>${badge(r.channel)}</td><td>${esc(r.purpose)}</td><td>${esc(r.date)}</td><td>${badge(r.status)}</td></tr>`).join("")||`<tr><td colspan="6">${empty("No reminders yet.")}</td></tr>`}</tbody></table></div>`}

function render(view=currentView){
 currentView=view; const titles={dashboard:["Dashboard","CM Filings compliance workspace"],clients:["Clients","Client master and contact records"],compliance:["Compliance Management","Track every statutory filing"],invoices:["Invoices","Invoice each compliance separately"],payments:["Payments","Payment requests and collection status"],calendar:["Compliance Calendar","Due dates and filing workload"],documents:["Documents","Client document vault"],credentials:["Credentials","Protected portal access records"],reminders:["Reminders","Client reminders and payment requests"],settings:["Settings","Application configuration"]};
 document.getElementById("pageTitle").textContent=titles[view][0];document.getElementById("pageSubtitle").textContent=titles[view][1];
 document.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("active",x.dataset.view===view));
 document.getElementById("viewContainer").innerHTML=views[view]();
 bindDynamic();
 if(view==="dashboard") drawChart();
}
function bindDynamic(){
 const cf=document.getElementById("clientFilter");if(cf)cf.oninput=()=>document.getElementById("clientTable").innerHTML=clientTable(store.clients.filter(c=>(c.name+" "+c.pan+" "+c.gstin).toLowerCase().includes(cf.value.toLowerCase())));
 const qf=document.getElementById("complianceFilter"),sf=document.getElementById("statusFilter");const filter=()=>{let q=(qf?.value||"").toLowerCase(),s=sf?.value||"";document.getElementById("complianceTable").innerHTML=complianceTable(store.compliances.filter(c=(!q||(c.type+" "+clientName(c.clientId)).toLowerCase().includes(q))&&(!s||c.status===s)))};if(qf)qf.oninput=filter;if(sf)sf.onchange=filter;
}
function drawChart(){const cv=document.getElementById("statusChart");if(!cv)return;const ctx=cv.getContext("2d"), counts=["Documents Pending","In Progress","Review","Filed","Completed"].map(s=>store.compliances.filter(c=>c.status===s).length);ctx.clearRect(0,0,cv.width,cv.height);const max=Math.max(...counts,1),w=cv.clientWidth,h=cv.clientHeight;cv.width=w*devicePixelRatio;cv.height=h*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio);const labels=["Docs Pending","In Progress","Review","Filed","Completed"];const barW=Math.max(28,(w-70)/labels.length-16);labels.forEach((l,i)=>{let x=35+i*(barW+16),bh=(counts[i]/max)*(h-60),y=h-35-bh;ctx.fillStyle=i===4?"#16A34A":"#B10000";ctx.globalAlpha=i===4?0.8:0.72;ctx.beginPath();ctx.roundRect(x,y,barW,bh,7);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle="#667085";ctx.font="9px Inter";ctx.textAlign="center";ctx.fillText(l,x+barW/2,h-17);ctx.fillStyle="#17181A";ctx.fillText(counts[i],x+barW/2,Math.max(12,y-7));});}
function modal(title,body,foot=""){document.getElementById("modalRoot").innerHTML=`<div class="modal-backdrop" id="activeModal"><div class="modal"><div class="modal-head"><h3>${title}</h3><button class="icon-btn" data-close-modal><i class="fa-solid fa-xmark"></i></button></div><div class="modal-body">${body}</div>${foot?`<div class="modal-foot">${foot}</div>`:""}</div></div>`}
function clientOptions(){return store.clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join("")}
function openClient(id=""){const c=store.clients.find(x=>x.id===id)||{};modal(id?"Edit Client":"New Client",`<form id="clientForm"><input type="hidden" name="id" value="${esc(c.id||"")}"><div class="form-grid"><div class="field"><label>Client / Legal Name *</label><input class="input" name="name" required value="${esc(c.name||"")}"></div><div class="field"><label>Entity Type</label><select class="select" name="type"><option ${c.type==="Individual"?"selected":""}>Individual</option><option ${c.type==="Proprietorship"?"selected":""}>Proprietorship</option><option ${c.type==="Partnership"?"selected":""}>Partnership</option><option ${c.type==="LLP"?"selected":""}>LLP</option><option ${c.type==="Company"?"selected":""}>Company</option></select></div><div class="field"><label>PAN *</label><input class="input" name="pan" required value="${esc(c.pan||"")}"></div><div class="field"><label>GSTIN</label><input class="input" name="gstin" value="${esc(c.gstin||"")}"></div><div class="field"><label>Mobile / WhatsApp</label><input class="input" name="mobile" value="${esc(c.mobile||"")}"></div><div class="field"><label>Email</label><input class="input" name="email" type="email" value="${esc(c.email||"")}"></div><div class="field"><label>City / District</label><input class="input" name="city" value="${esc(c.city||"")}"></div><div class="field"><label>Assigned Staff</label><input class="input" name="assignee" value="${esc(c.assignee||"Admin Principal")}"></div><div class="field"><label>Status</label><select class="select" name="status"><option>Active</option><option>Inactive</option><option>Archived</option></select></div><div class="field full"><label>Address</label><textarea class="textarea" name="address" rows="3">${esc(c.address||"")}</textarea></div></div></form>`,`<button class="btn-secondary" data-close-modal>Cancel</button><button class="primary" form="clientForm">Save Client</button>`)}
function openCompliance(id=""){const c=store.compliances.find(x=>x.id===id)||{};modal(id?"Edit Compliance":"New Compliance",`<form id="complianceForm"><input type="hidden" name="id" value="${esc(c.id||"")}"><div class="form-grid"><div class="field"><label>Client *</label><select class="select" name="clientId" required>${clientOptions()}</select></div><div class="field"><label>Compliance Type *</label><select class="select" name="type"><option>GSTR-1</option><option>GSTR-3B</option><option>GSTR-9</option><option>TDS 24Q</option><option>TDS 26Q</option><option>Income Tax Return</option><option>Advance Tax</option><option>ROC Annual Filing</option><option>PF / ESI</option><option>FSSAI</option><option>Other</option></select></div><div class="field"><label>Period / FY</label><input class="input" name="period" value="${esc(c.period||"Oct 2026")}"></div><div class="field"><label>Statutory Due Date *</label><input class="input" type="date" name="due" required value="${esc(c.due||"")}"></div><div class="field"><label>Professional Fee</label><input class="input" type="number" name="fee" value="${esc(c.fee||0)}"></div><div class="field"><label>Assigned Staff</label><input class="input" name="assignee" value="${esc(c.assignee||"Admin Principal")}"></div><div class="field"><label>Status</label><select class="select" name="status"><option>Documents Pending</option><option>In Progress</option><option>Review</option><option>Filed</option><option>Completed</option><option>Overdue</option></select></div><div class="field"><label>Payment Status</label><select class="select" name="payment"><option>Pending</option><option>Requested</option><option>Partially Paid</option><option>Paid</option><option>Overdue</option></select></div><div class="field"><label>Document Status</label><select class="select" name="docs"><option>Pending</option><option>Received</option><option>Verified</option></select></div><div class="field full"><label>Notes</label><textarea class="textarea" name="notes" rows="3">${esc(c.notes||"")}</textarea></div></div></form>`,`<button class="btn-secondary" data-close-modal>Cancel</button><button class="primary" form="complianceForm">Save Compliance</button>`);const f=document.getElementById("complianceForm");if(c.clientId)f.clientId.value=c.clientId;if(c.type)f.type.value=c.type;if(c.status)f.status.value=c.status;if(c.payment)f.payment.value=c.payment;if(c.docs)f.docs.value=c.docs}
function openInvoice(){modal("Create Compliance Invoice",`<form id="invoiceForm"><div class="form-grid"><div class="field"><label>Client</label><select class="select" name="clientId">${clientOptions()}</select></div><div class="field"><label>Compliance</label><select class="select" name="compliance">${store.compliances.map(c=>`<option value="${c.id}">${esc(c.type)} — ${esc(clientName(c.clientId))}</option>`).join("")}</select></div><div class="field"><label>Professional Fee</label><input class="input" type="number" name="fee" value="0"></div><div class="field"><label>GST %</label><input class="input" type="number" name="gst" value="18"></div><div class="field"><label>Invoice Date</label><input class="input" type="date" name="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Payment Due Date</label><input class="input" type="date" name="due"></div></div></form>`,`<button class="btn-secondary" data-close-modal>Cancel</button><button class="primary" form="invoiceForm">Create Invoice</button>`)}
function openPayment(clientId="",purpose=""){modal("Request Payment",`<form id="paymentForm"><div class="form-grid"><div class="field"><label>Client</label><select class="select" name="clientId">${clientOptions()}</select></div><div class="field"><label>Amount</label><input class="input" type="number" name="amount" required value="0"></div><div class="field full"><label>Purpose</label><input class="input" name="purpose" required value="${esc(purpose)}" placeholder="GSTR-3B filing fee"></div><div class="field"><label>Payment Method</label><select class="select" name="method"><option>UPI / QR</option><option>Payment Gateway</option><option>Bank Transfer</option></select></div><div class="field"><label>Due Date</label><input class="input" type="date" name="due"></div></div></form>`,`<button class="btn-secondary" data-close-modal>Cancel</button><button class="primary" form="paymentForm">Create Payment Request</button>`);if(clientId)document.querySelector("#paymentForm [name=clientId]").value=clientId}
function openCredential(){modal("Add Credential",`<form id="credentialForm"><div class="form-grid"><div class="field"><label>Client</label><select class="select" name="clientId">${clientOptions()}</select></div><div class="field"><label>Portal / Service</label><input class="input" name="portal" placeholder="GST Portal"></div><div class="field"><label>Username</label><input class="input" name="username"></div><div class="field"><label>Password</label><input class="input" name="password" type="password"></div><div class="field full"><label>Notes</label><textarea class="textarea" name="notes"></textarea></div></div></form>`,`<button class="btn-secondary" data-close-modal>Cancel</button><button class="primary" form="credentialForm">Save Credential</button>`)}
function openReminder(){modal("New Reminder",`<form id="reminderForm"><div class="form-grid"><div class="field"><label>Client</label><select class="select" name="clientId">${clientOptions()}</select></div><div class="field"><label>Channel</label><select class="select" name="channel"><option>WhatsApp</option><option>Email</option><option>SMS</option><option>Internal</option></select></div><div class="field full"><label>Purpose</label><input class="input" name="purpose" required placeholder="Documents pending / payment reminder"></div><div class="field"><label>Schedule Date</label><input class="input" type="date" name="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Status</label><select class="select" name="status"><option>Scheduled</option><option>Sent</option><option>Pending</option></select></div></div></form>`,`<button class="btn-secondary" data-close-modal>Cancel</button><button class="primary" form="reminderForm">Save Reminder</button>`)}
function openUpload(){modal("Upload Client Document",`<form id="uploadForm"><div class="form-grid"><div class="field"><label>Client</label><select class="select" name="clientId">${clientOptions()}</select></div><div class="field"><label>Category</label><select class="select" name="category"><option>KYC</option><option>GST</option><option>Income Tax</option><option>TDS</option><option>ROC</option><option>Financials</option><option>Other</option></select></div><div class="field full"><label>Choose File</label><input class="input" type="file" name="file" required></div></div><div class="notice warning" style="margin-top:12px">Demo mode stores file metadata in local storage. Production should use Firebase Storage.</div></form>`,`<button class="btn-secondary" data-close-modal>Cancel</button><button class="primary" form="uploadForm">Upload</button>`)}
function handleForm(form,type){
 const fd=new FormData(form),o=Object.fromEntries(fd.entries());
 if(type==="client"){let id=o.id||"CL-"+String(store.clients.length+1).padStart(4,"0"),old=store.clients.find(x=>x.id===id);const n={...old,...o,id};old?Object.assign(old,n):store.clients.unshift(n)}
 if(type==="compliance"){let id=o.id||"CMP-"+String(store.compliances.length+1).padStart(4,"0"),old=store.compliances.find(x=>x.id===id);const n={...old,...o,fee:Number(o.fee||0),id};old?Object.assign(old,n):store.compliances.unshift(n)}
 if(type==="invoice"){const fee=Number(o.fee||0),gst=fee*Number(o.gst||0)/100;store.invoices.unshift({id:"INV-"+String(store.invoices.length+1).padStart(5,"0"),clientId:o.clientId,compliance:store.compliances.find(c=>c.id===o.compliance)?.type||"Compliance",fee,gst,total:fee+gst,date:o.date,due:o.due,status:"Unpaid"})}
 if(type==="payment"){store.payments.unshift({id:"PAY-"+String(store.payments.length+1).padStart(5,"0"),...o,amount:Number(o.amount||0),date:new Date().toISOString().slice(0,10),status:"Requested"})}
 if(type==="credential"){store.credentials.unshift({id:"CRD-"+Date.now(),...o,date:new Date().toISOString().slice(0,10)})}
 if(type==="reminder"){store.reminders.unshift({id:"REM-"+String(store.reminders.length+1).padStart(5,"0"),...o})}
 save();document.getElementById("modalRoot").innerHTML="";render(currentView);toast("Saved successfully")}
document.addEventListener("click",e=>{
 const v=e.target.closest("[data-view]");if(v){render(v.dataset.view);document.getElementById("sidebar").classList.remove("open");return}
 const a=e.target.closest("[data-action]");if(a){const x=a.dataset.action;if(x==="new-client")openClient();if(x==="new-compliance")openCompliance();if(x==="new-invoice")openInvoice();if(x==="new-payment")openPayment();if(x==="new-credential")openCredential();if(x==="new-reminder")openReminder();if(x==="upload-doc")openUpload();if(x==="reset-data"){localStorage.clear();location.reload()}return}
 if(e.target.closest("[data-close-modal]"))document.getElementById("modalRoot").innerHTML="";
 const ec=e.target.closest("[data-edit-client]");if(ec)openClient(ec.dataset.editClient);
 const ed=e.target.closest("[data-delete-client]");if(ed&&confirm("Delete this client?")){store.clients=store.clients.filter(c=>c.id!==ed.dataset.deleteClient);save();render("clients")}
 const ecmp=e.target.closest("[data-edit-compliance]");if(ecmp)openCompliance(ecmp.dataset.editCompliance);
 const pay=e.target.closest("[data-payment]");if(pay)openPayment(store.compliances.find(c=>c.id===pay.dataset.payment)?.clientId,"Payment for "+store.compliances.find(c=>c.id===pay.dataset.payment)?.type);
 const mp=e.target.closest("[data-mark-paid]");if(mp){const p=store.payments.find(x=>x.id===mp.dataset.markPaid);if(p){p.status="Paid";save();render("payments");toast("Payment marked as paid")}}
 const cred=e.target.closest("[data-delete-cred]");if(cred){store.credentials=store.credentials.filter(x=>x.id!==cred.dataset.deleteCred);save();render("credentials")}
 const pass=e.target.closest("[data-show-pass]");if(pass){const c=store.credentials.find(x=>x.id===pass.dataset.showPass);if(c)toast("Password: "+c.password)}
 const pi=e.target.closest("[data-print-invoice]");if(pi)printInvoice(store.invoices.find(x=>x.id===pi.dataset.printInvoice));
 const dd=e.target.closest("[data-download-doc]");if(dd){const d=store.documents.find(x=>x.id===dd.dataset.downloadDoc);if(d?.data){const a=document.createElement("a");a.href=d.data;a.download=d.name;a.click()}else toast("Document metadata available; connect Firebase Storage for production files.")}
});
document.addEventListener("submit",e=>{if(!e.target.id)return;e.preventDefault();const id=e.target.id;if(id==="clientForm")handleForm(e.target,"client");if(id==="complianceForm")handleForm(e.target,"compliance");if(id==="invoiceForm")handleForm(e.target,"invoice");if(id==="paymentForm")handleForm(e.target,"payment");if(id==="credentialForm")handleForm(e.target,"credential");if(id==="reminderForm")handleForm(e.target,"reminder");if(id==="uploadForm"){const f=e.target.file.files[0],r=new FileReader();r.onload=()=>{store.documents.unshift({id:"DOC-"+Date.now(),clientId:e.target.clientId.value,name:f.name,category:e.target.category.value,date:new Date().toISOString().slice(0,10),size:(f.size/1048576).toFixed(2)+" MB",data:r.result});save();document.getElementById("modalRoot").innerHTML="";render("documents");toast("Document uploaded")};r.readAsDataURL(f)}});
document.getElementById("menuBtn").onclick=()=>document.getElementById("sidebar").classList.toggle("open");
function printInvoice(i){if(!i)return;const w=window.open("","_blank");w.document.write(`<html><head><title>${i.id}</title><style>body{font-family:Arial;padding:40px}h1{color:#B10000}table{width:100%;border-collapse:collapse}td,th{padding:10px;border-bottom:1px solid #ddd;text-align:left}</style></head><body><h1>CM FILINGS</h1><h2>Invoice ${i.id}</h2><p>Client: ${esc(clientName(i.clientId))}</p><table><tr><th>Compliance</th><td>${esc(i.compliance)}</td></tr><tr><th>Professional Fee</th><td>${money(i.fee)}</td></tr><tr><th>GST</th><td>${money(i.gst)}</td></tr><tr><th>Total</th><td><b>${money(i.total)}</b></td></tr></table><p>Thank you.</p><script>window.print()</script></body></html>`);w.document.close()}
function toast(msg){const t=document.createElement("div");t.style.cssText="position:fixed;right:18px;bottom:82px;background:#17181A;color:#fff;padding:12px 15px;border-radius:10px;font-size:11px;z-index:200;box-shadow:0 10px 30px #0003";t.innerHTML='<i class="fa-solid fa-circle-check" style="color:#16A34A;margin-right:8px"></i>'+esc(msg);document.getElementById("toastRoot").appendChild(t);setTimeout(()=>t.remove(),3000)}
window.addEventListener("resize",()=>{if(currentView==="dashboard")drawChart()});
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});
render();
