import { initializeApp } from "https://www.gstatic.com/firebasejs/10.10.0/firebase-app.js";
import { getAuth, signInWithEmailAndPassword, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/10.10.0/firebase-auth.js";
import { getFirestore, collection, getDocs, addDoc, updateDoc, deleteDoc, doc, orderBy, query } from "https://www.gstatic.com/firebasejs/10.10.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyCXyKSTlmlzkYnH2LW408cVVWV1CPvlfBo",authDomain:"cmfilings-6a37c.firebaseapp.com",projectId:"cmfilings-6a37c",storageBucket:"cmfilings-6a37c.firebasestorage.app",messagingSenderId:"138705123778",appId:"1:138705123778:web:9561bff9f0f5d89bb6fe5b",measurementId:"G-09DM4NZF8D"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
let clients=[],myLinks=[],myNotes=[],sortMode=localStorage.getItem('cmContactsSort')||'name';
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function icons(){if(window.lucide)lucide.createIcons()}
icons();
if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(console.warn);

const loginView=$('loginView'),appView=$('appView'),loginForm=$('loginForm'),loginBtn=$('loginBtn'),loginBtnText=$('loginBtnText'),loginLoader=$('loginLoader'),loginError=$('loginError'),logoutBtn=$('logoutBtn');
$('togglePwdBtn').addEventListener('click',()=>{const p=$('passwordInput'),i=$('pwdIcon'),t=p.type==='password'?'text':'password';p.type=t;i.setAttribute('data-lucide',t==='text'?'eye-off':'eye');icons()});
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(id).classList.add('active')}
function setLoginLoading(x){loginBtn.disabled=x;loginBtnText.style.display=x?'none':'block';loginLoader.style.display=x?'block':'none'}
loginForm.addEventListener('submit',async e=>{e.preventDefault();loginError.textContent='';setLoginLoading(true);try{await signInWithEmailAndPassword(auth,$('emailInput').value.trim(),$('passwordInput').value)}catch(err){console.error(err);loginError.textContent='Invalid email or password.'}finally{setLoginLoading(false)}});
logoutBtn.addEventListener('click',()=>signOut(auth));

document.querySelectorAll('.nav-item').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(n=>n.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.tab-content').forEach(t=>t.classList.remove('active'));$(btn.dataset.target).classList.add('active')}));

function initials(n){return n?String(n).trim().substring(0,1).toUpperCase():'?'}
function wa(m){const n=String(m||'').replace(/\D/g,'');if(!n)return '';return `https://wa.me/${n.length===10?'91'+n:n}`}
function validPhone(m){return String(m||'').trim().length>0}
function renderContacts(search=''){
 const box=$('contactList'); let q=search.toLowerCase().trim();
 let filtered=clients.filter(c=>[c.name,c.id,c.mobile].some(v=>String(v||'').toLowerCase().includes(q)));
 filtered.sort((a,b)=>sortMode==='id'?String(a.id).localeCompare(String(b.id),undefined,{numeric:true,sensitivity:'base'}):String(a.name).localeCompare(String(b.name),undefined,{numeric:true,sensitivity:'base'}));
 if(!filtered.length){box.innerHTML='<div class="flex flex-col items-center justify-center h-48 text-[var(--m3-text-muted)]"><i data-lucide="search-x" class="w-10 h-10 mb-2"></i><p>No clients found.</p></div>';icons();return}
 box.innerHTML=filtered.map(c=>{const has=validPhone(c.mobile);return `<div class="contact-item"><div class="avatar">${esc(initials(c.name))}</div><div class="contact-info"><div class="contact-name">${esc(c.name)}</div><div class="contact-id">ID: ${esc(c.id)}${has?` · ${esc(c.mobile)}`:''}</div></div><div class="contact-actions">${has?`<a href="${esc(wa(c.mobile))}" target="_blank" rel="noopener noreferrer" class="action-btn action-whatsapp" title="WhatsApp"><i data-lucide="message-circle" class="w-[22px] h-[22px]"></i></a><a href="tel:${esc(c.mobile)}" class="action-btn action-call" title="Call"><i data-lucide="phone" class="w-[22px] h-[22px]"></i></a>`:''}</div></div>`}).join('');icons();
}
$('sortSelect').value=sortMode;$('sortSelect').addEventListener('change',e=>{sortMode=e.target.value;localStorage.setItem('cmContactsSort',sortMode);renderContacts($('searchInput').value)});$('searchInput').addEventListener('input',e=>renderContacts(e.target.value));

$('importContactsBtn').addEventListener('click',async()=>{if(!('contacts' in navigator)&&!('ContactsManager' in window)){alert('Contact Picker API is not supported on this browser/device. Try Chrome on Android.');return}try{const picked=await navigator.contacts.select(['name','tel'],{multiple:true});if(!picked.length)return;const btn=$('importContactsBtn');btn.disabled=true;btn.innerHTML='<div class="animate-spin rounded-full h-[22px] w-[22px] border-b-2 border-[var(--m3-primary)]"></div>';for(const c of picked){const name=c.name?.[0]?.trim()||'Unknown Contact',phone=c.tel?.[0]||'';await addDoc(collection(db,'clients'),{clientId:'C'+Date.now().toString().slice(-6)+Math.floor(Math.random()*10),clientName:name,mobile:phone,isSavedInPhone:true,createdAt:Date.now()})}alert(`${picked.length} contact(s) imported to database!`);await fetchClients()}catch(err){console.error(err);if(err.name!=='AbortError')alert('Import failed. Please ensure contact permission is granted.')}finally{$('importContactsBtn').disabled=false;$('importContactsBtn').innerHTML='<i data-lucide="book-user" class="w-[22px] h-[22px]"></i>';icons()}});

async function fetchClients(){const box=$('contactList');box.innerHTML='<div class="flex justify-center items-center h-24"><div class="animate-spin rounded-full h-8 w-8 border-b-2 border-[var(--m3-primary)]"></div></div>';try{const snap=await getDocs(collection(db,'clients'));clients=[];snap.forEach(d=>{const x=d.data();clients.push({id:x.clientId||d.id,name:x.clientName||'Unknown Name',mobile:x.mobile||''})});renderContacts();populateDatalist()}catch(e){console.error(e);box.innerHTML='<div class="flex flex-col items-center justify-center h-48 text-[var(--m3-error)]"><i data-lucide="alert-circle" class="w-10 h-10 mb-2"></i><p>Failed to load clients.</p></div>';icons()}}
function populateDatalist(){$('clientDatalist').innerHTML=clients.map(c=>`<option value="${esc(c.name)} (${esc(c.id)})"></option>`).join('')}

const linkForm=$('linkForm');function renderLinks(){const c=$('linksListContainer');if(!myLinks.length){c.innerHTML='<p class="text-center text-sm text-[var(--m3-text-muted)] mt-4">No links saved yet.</p>';return}c.innerHTML=myLinks.map(l=>`<div class="data-card flex items-center justify-between"><div class="flex-1 min-w-0 pr-3"><h3 class="font-semibold text-[1.05rem] truncate text-[var(--m3-primary)]">${esc(l.name)}</h3><p class="text-xs text-[var(--m3-text-muted)] truncate">${esc(l.url)}</p></div><div class="flex items-center gap-1"><button onclick="window.openIframe(${JSON.stringify(l.url)},${JSON.stringify(l.name)})" class="action-btn !text-[var(--m3-primary)]" title="Visit"><i data-lucide="external-link" class="w-5 h-5"></i></button><button onclick="window.editLink('${esc(l.id)}')" class="action-btn !text-[var(--m3-text-muted)]" title="Edit"><i data-lucide="edit-2" class="w-4 h-4"></i></button><button onclick="window.deleteLink('${esc(l.id)}')" class="action-btn !text-[var(--m3-error)]" title="Delete"><i data-lucide="trash-2" class="w-4 h-4"></i></button></div></div>`).join('');icons()}
async function fetchLinks(){try{const s=await getDocs(query(collection(db,'links')));myLinks=[];s.forEach(d=>myLinks.push({id:d.id,...d.data()}));renderLinks()}catch(e){console.error(e)}}
function resetLinkForm(){$('editLinkId').value='';$('linkSubmitBtn').textContent='Add Link';$('linkCancelBtn').classList.add('hidden');linkForm.reset()}
linkForm.addEventListener('submit',async e=>{e.preventDefault();const id=$('editLinkId').value;let url=$('linkUrl').value.trim();if(!/^https?:\/\//i.test(url))url='https://'+url;const data={name:$('linkName').value.trim(),url,timestamp:Date.now()};$('linkSubmitBtn').disabled=true;try{if(id){await updateDoc(doc(db,'links',id),data);const i=myLinks.findIndex(x=>x.id===id);if(i>-1)myLinks[i]={id,...data}}else{const r=await addDoc(collection(db,'links'),data);myLinks.push({id:r.id,...data})}renderLinks();resetLinkForm()}catch(e){console.error(e);alert('Could not save link.')}finally{$('linkSubmitBtn').disabled=false;$('linkSubmitBtn').textContent=id?'Update Link':'Add Link'}});$('linkCancelBtn').addEventListener('click',resetLinkForm);
window.editLink=id=>{const l=myLinks.find(x=>x.id===id);if(!l)return;$('editLinkId').value=l.id;$('linkName').value=l.name;$('linkUrl').value=l.url;$('linkSubmitBtn').textContent='Update Link';$('linkCancelBtn').classList.remove('hidden')};window.deleteLink=async id=>{if(!confirm('Delete this link?'))return;try{await deleteDoc(doc(db,'links',id));myLinks=myLinks.filter(x=>x.id!==id);renderLinks()}catch(e){console.error(e)}};
window.openIframe=(url,name)=>{$('iframeTitle').textContent=name||url;$('contentIframe').src=url;$('iframeModal').classList.remove('hidden');$('iframeModal').classList.add('flex');icons()};window.closeIframe=()=>{$('iframeModal').classList.add('hidden');$('iframeModal').classList.remove('flex');$('contentIframe').src=''};

const noteForm=$('noteForm');
function noteDate(v){try{return new Date(v).toLocaleString([],{month:'short',day:'numeric',year:'numeric',hour:'2-digit',minute:'2-digit'})}catch{return v}}
function renderNotes(){const c=$('notesListContainer');if(!myNotes.length){c.innerHTML='<p class="text-center text-sm text-[var(--m3-text-muted)] mt-4">No notes saved yet.</p>';return}const arr=[...myNotes].sort((a,b)=>Number(b.timestamp||0)-Number(a.timestamp||0));c.innerHTML=arr.map(n=>{const due=n.reminder?new Date(n.reminder).getTime()<=Date.now():false;return `<div class="data-card relative"><button onclick="window.deleteNote('${esc(n.id)}')" class="absolute top-3 right-3 text-[var(--m3-text-muted)] bg-transparent border-none" title="Delete"><i data-lucide="x" class="w-4 h-4"></i></button><h3 class="font-semibold text-[1.05rem] pr-6">${esc(n.clientRef)}</h3><p class="text-sm mt-2 text-[var(--m3-text-variant)] whitespace-pre-wrap">${esc(n.content)}</p>${n.reminder?`<div class="flex items-center gap-1 text-xs font-medium ${due?'text-[var(--m3-error)]':'text-[var(--m3-primary)]'} mt-3 bg-[var(--m3-primary-container)] w-max px-2 py-1 rounded-md"><i data-lucide="bell" class="w-3 h-3"></i>${esc(noteDate(n.reminder))}${due?' · Due':''}</div>`:''}</div>`}).join('');icons()}
async function fetchNotes(){try{let s;try{s=await getDocs(query(collection(db,'notes'),orderBy('timestamp','desc')))}catch{s=await getDocs(collection(db,'notes'))}myNotes=[];s.forEach(d=>myNotes.push({id:d.id,...d.data()}));renderNotes();checkReminders()}catch(e){console.error(e)}}
noteForm.addEventListener('submit',async e=>{e.preventDefault();const reminder=$('noteReminder').value;const data={clientRef:$('noteClient').value.trim(),content:$('noteContent').value.trim(),reminder,timestamp:Date.now(),reminderNotified:false};$('noteSubmitBtn').disabled=true;try{if(reminder&&'Notification' in window&&Notification.permission==='default')await Notification.requestPermission();const r=await addDoc(collection(db,'notes'),data);myNotes.push({id:r.id,...data});renderNotes();noteForm.reset();checkReminders()}catch(e){console.error(e);alert('Could not save note.')}finally{$('noteSubmitBtn').disabled=false;$('noteSubmitBtn').textContent='Save Note'}});
window.deleteNote=async id=>{if(!confirm('Delete this note?'))return;try{await deleteDoc(doc(db,'notes',id));myNotes=myNotes.filter(n=>n.id!==id);renderNotes()}catch(e){console.error(e)}};
async function notifyReminder(n){const title='CM Contacts Reminder';const body=`${n.clientRef}: ${n.content}`;if('Notification' in window&&Notification.permission==='granted'){new Notification(title,{body,tag:'note-'+n.id})}else{alert(`${title}\n\n${body}`)}}
async function checkReminders(){const now=Date.now();for(const n of myNotes){if(!n.reminder||n.reminderNotified)continue;const t=new Date(n.reminder).getTime();if(Number.isFinite(t)&&t<=now){try{await notifyReminder(n);await updateDoc(doc(db,'notes',n.id),{reminderNotified:true});n.reminderNotified=true}catch(e){console.error('Reminder error',e)}}}renderNotes()}
setInterval(checkReminders,15000);

const aiForm=$('aiChatForm'),aiInput=$('aiInput'),chat=$('chatHistory'),send=$('aiSendBtn');let chatMessages=[];
function appendMessage(text,sender,typing=false){const d=document.createElement('div');d.className=`p-3 rounded-2xl text-sm max-w-[85%] ${sender==='user'?'bg-[var(--m3-primary)] text-white self-end rounded-tr-sm':'bg-[var(--m3-surface-container)] text-[var(--m3-text-main)] self-start rounded-tl-sm'} ${typing?'animate-pulse':''}`;d.textContent=text;chat.appendChild(d);chat.scrollTop=chat.scrollHeight;return d}
aiForm.addEventListener('submit',async e=>{e.preventDefault();const text=aiInput.value.trim();if(!text)return;appendMessage(text,'user');aiInput.value='';send.disabled=true;const context=`Clients: ${JSON.stringify(clients.map(c=>({name:c.name,mobile:c.mobile,id:c.id})))}\nNotes: ${JSON.stringify(myNotes.map(n=>({client:n.clientRef,content:n.content,reminder:n.reminder})))}\nLinks: ${JSON.stringify(myLinks.map(l=>({name:l.name,url:l.url})))}`;chatMessages.push({role:'user',parts:[{text}]});const key='YOUR_GEMINI_API_KEY';const typing=appendMessage('...','model',true);try{if(key==='YOUR_GEMINI_API_KEY')throw new Error('Missing API Key');const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${key}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:chatMessages,systemInstruction:{parts:[{text:`You are the CM Contacts assistant. Answer concisely using this context:\n${context}`}]}})});const j=await r.json();typing.remove();const t=j.candidates?.[0]?.content?.parts?.[0]?.text;if(t){chatMessages.push({role:'model',parts:[{text:t}]});appendMessage(t,'model')}else appendMessage('Sorry, I could not process that.','model')}catch(e){typing.remove();appendMessage(e.message==='Missing API Key'?'Add the Gemini API key through a secure backend before enabling AI.':'An error occurred connecting to the AI assistant.','model')}finally{send.disabled=false}});

onAuthStateChanged(auth,user=>{if(user){showView('appView');fetchClients();fetchLinks();fetchNotes()}else{showView('loginView');clients=[];myLinks=[];myNotes=[];renderContacts();renderLinks();renderNotes()}});
